##
## Copyright (c) 2020-2021 NVIDIA CORPORATION.  All rights reserved.
##
## NVIDIA CORPORATION and its licensors retain all intellectual property
## and proprietary rights in and to this software, related documentation
## and any modifications thereto.  Any use, reproduction, disclosure or
## distribution of this software and related documentation without an express
## license agreement from NVIDIA CORPORATION is strictly prohibited.
##
##

# @package _global_
use_cuda: True
cuda_device_num: 0

control_dt: 0.001
#dynamics_dt: 0.01
run_open_loop: False
control_space: 'acc'
float_dtype: 'float32'
model:
  # any link that is not specified as learnable will be initialized from urdf
  urdf_path: "urdf/franka_description/franka_panda_no_gripper.urdf"
  learnable_rigid_body_config:
    learnable_links: []
  name: "franka_panda"
  dt: 0.01
  max_acc: 0.5 #10.0

  dt_traj_params:
    base_dt: 0.01
    base_ratio: 0.4
    max_dt: 0.2
  #control_freq: 10
  #sim_freq: 100
  ee_link_name: "ee_link"
  init_state: [0.8, 0.3, 0.0, -1.57, 0.0, 1.86, 0.]
  link_names: ['panda_link3', 'panda_link4', 'panda_link5', 'panda_link6','panda_link7','panda_hand']

  collision_model:
    link_objs:
      panda_hand:
        base: [0.0, 0.0, 0.0]
        tip: [0.0, 0.05, 0.0]
        radius: 0.06
        pose_offset: [0.0, 0.0, 0.12, 0.0, 0.0, 0.0] # x,y,z, r,p,y


cost:
  goal_pose:
    vec_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    weight: [0.01,100.0]
    position_gaussian_params: {'n':0, 'c':0.2, 's':0.0, 'r':10.0}
    orientation_gaussian_params: {'n':0, 'c':0.2, 's':0.0, 'r':10.0}
    hinge_val: -1
    convergence_val: [0.0, 0.0] # orientation, position

  zero_vel:
    weight: 0.0
    hinge_val: 0.2 #0.2
    gaussian_params: {'n':0, 'c':0.2, 's':0, 'r':1.0}

  zero_acc:
    weight: 0.0 #0.01
    hinge_val: -1.0
    gaussian_params: {'n':0, 'c':0.2, 's':0, 'r':5.0}
  
  collision:
    weight: 0.0
    gaussian_params: {'n':0, 'c':0.5, 's':0, 'r':5.0}
    
  primitive_collision:
    weight: 0.0
    gaussian_params: {'n':0, 'c':0.8, 's':0, 'r':10.0}

  null_space:
    weight: 100.0 #0.05 #0.5 #1.0
    gaussian_params: {'n':0, 'c':0.5, 's':0, 'r':1.0}
    # vec_weight: [0.0, 1.0, 0.0, 0.1, 0.1, 0.0, 0.1]
    vec_weight: [0.0, 0.1, 0.1, 1.0, 1.0, 0.1, 0.0]
    #retract_state : [-1.57, -1.2, 1.9, -1.383, -1.57, 0.00]
  jacobian_cost_weight: 0.0 #2

  joint_l2:
    weight: 0.0
    gaussian_params: {'n':0, 'c':0.2, 's':0, 'r':5.0}

  ee_vel:
    weight: 0.0
    vec_weight: [1.0, 1.0, 1.0, 0.0, 0.0, 0.0]
    gaussian_params: {'n':0, 'c':0.2, 's':0.0, 'r':5.0}
    
  scene_collision:
    weight: 00.0 #5000.0
    gaussian_params: {'n':0, 'c':0.8, 's':0, 'r':10.0}
    
  stop_cost:
    weight: 1000.0
    max_acc: 0.1 #0.2
    gaussian_params: {'n':0, 'c':0.2, 's':0, 'r':5.0}


  voxel_collision:
    weight: 0.0 #5000.0
    gaussian_params: {'n':0, 'c':0.8, 's':0, 'r':10.0}
    distance_threshold: 0.01


  smooth: # on robot acceleration
    weight: 1000.0
    gaussian_params: {'n':0, 'c':1.0, 's':0, 'r':10.0}
    order: 3

  control_cost_weight: 0.0
  jerk_cost_weight: 0.0
  
  retract_state : [0.0, -0.2, 0.0, -1.57, 0.0, 1.86, 0.]
  retract_weight: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0,0.0]

mppi:
  horizon           : 50
  init_cov          : 0.01 #.5
  gamma             : 0.99
  n_iters           : 1
  step_size_mean    : 0.9 #0.05 #0.05
  step_size_cov     : 0.6
  beta              : 0.1 #1.0
  alpha             : 1
  num_particles     : 500 #10000
  update_cov        : False
  cov_type          : 'diag_AxA' # 
  kappa             : 0.001
  null_act_frac     : 0.01 #0.1
  sample_mode       : 'mean'
  base_action       : 'null'
  squash_fn         : 'clamp'
  hotstart          : True
  visual_traj       : 'ee_pos_seq'
  sample_params:
    type: 'halton_stomp'
    fixed_samples: True
    sample_ratio: 0.4
    seed: 0
    filter_coeffs: [0.25, 0.8, 0.0]

